import { FeatureCatalogItem } from './entitlements.model';

export interface FeatureTemplate {
  featureKey: string;
  displayName: string;
  module: string;
  dependencies: string[];
  filters?: Array<{
    key: string;
    defaultValue: string | number | boolean | null;
  }>;
}

export const FEATURE_TEMPLATES: FeatureTemplate[] = [
  { featureKey: 'package.managetiers', displayName: 'Manage Package Tiers', module: 'saas-platform', dependencies: [] },
  { featureKey: 'category.list', displayName: 'View Categories', module: 'masters', dependencies: [] },
  { featureKey: 'category.view', displayName: 'View Category', module: 'masters', dependencies: ['category.list'] },
  { featureKey: 'category.create', displayName: 'Create Category', module: 'masters', dependencies: [] },
  { featureKey: 'category.edit', displayName: 'Edit Category', module: 'masters', dependencies: ['category.list'] },
  { featureKey: 'category.delete', displayName: 'Delete Category', module: 'masters', dependencies: ['category.list'] },
  { featureKey: 'field.list', displayName: 'View Fields', module: 'masters', dependencies: [] },
  { featureKey: 'field.view', displayName: 'View Field', module: 'masters', dependencies: ['field.list'] },
  { featureKey: 'field.create', displayName: 'Create Field', module: 'masters', dependencies: [] },
  { featureKey: 'field.edit', displayName: 'Edit Field', module: 'masters', dependencies: ['field.list'] },
  { featureKey: 'field.delete', displayName: 'Delete Field', module: 'masters', dependencies: ['field.list'] },
  { featureKey: 'field.bulk_create', displayName: 'Bulk Create Fields', module: 'masters', dependencies: ['field.create'] },
  { featureKey: 'attribute.list', displayName: 'View Attributes', module: 'masters', dependencies: [] },
  { featureKey: 'attribute.view', displayName: 'View Attribute', module: 'masters', dependencies: ['attribute.list'] },
  { featureKey: 'attribute.create', displayName: 'Create Attribute', module: 'masters', dependencies: [], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'attribute.edit', displayName: 'Edit Attribute', module: 'masters', dependencies: ['attribute.list'] },
  { featureKey: 'attribute.delete', displayName: 'Delete Attribute', module: 'masters', dependencies: ['attribute.list'] },
  { featureKey: 'fieldGroup.list', displayName: 'View Field Groups', module: 'masters', dependencies: [] },
  { featureKey: 'fieldGroup.view', displayName: 'View Field Group', module: 'masters', dependencies: ['fieldGroup.list'] },
  { featureKey: 'fieldGroup.create', displayName: 'Create Field Group', module: 'masters', dependencies: [] },
  { featureKey: 'fieldGroup.edit', displayName: 'Edit Field Group', module: 'masters', dependencies: ['fieldGroup.list'] },
  { featureKey: 'fieldGroup.delete', displayName: 'Delete Field Group', module: 'masters', dependencies: ['fieldGroup.list'] },
  { featureKey: 'attributeSet.list', displayName: 'View Attribute Sets', module: 'masters', dependencies: [] },
  { featureKey: 'attributeSet.view', displayName: 'View Attribute Set', module: 'masters', dependencies: ['attributeSet.list'] },
  { featureKey: 'attributeSet.create', displayName: 'Create Attribute Set', module: 'masters', dependencies: [], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'attributeSet.edit', displayName: 'Edit Attribute Set', module: 'masters', dependencies: ['attributeSet.list'] },
  { featureKey: 'attributeSet.delete', displayName: 'Delete Attribute Set', module: 'masters', dependencies: ['attributeSet.list'] },
  { featureKey: 'unit.list', displayName: 'View Units', module: 'masters', dependencies: [] },
  { featureKey: 'unit.view', displayName: 'View Unit', module: 'masters', dependencies: ['unit.list'] },
  { featureKey: 'unit.create', displayName: 'Create Unit', module: 'masters', dependencies: [] },
  { featureKey: 'unit.edit', displayName: 'Edit Unit', module: 'masters', dependencies: ['unit.list'] },
  { featureKey: 'unit.delete', displayName: 'Delete Unit', module: 'masters', dependencies: ['unit.list'] },
  { featureKey: 'taxProfile.list', displayName: 'View Tax Profiles', module: 'masters', dependencies: [] },
  { featureKey: 'taxProfile.view', displayName: 'View Tax Profile', module: 'masters', dependencies: ['taxProfile.list'] },
  { featureKey: 'taxProfile.create', displayName: 'Create Tax Profile', module: 'masters', dependencies: [] },
  { featureKey: 'taxProfile.edit', displayName: 'Edit Tax Profile', module: 'masters', dependencies: ['taxProfile.list'] },
  { featureKey: 'taxProfile.delete', displayName: 'Delete Tax Profile', module: 'masters', dependencies: ['taxProfile.list'] },
  { featureKey: 'pricingTemplate.list', displayName: 'View Pricing Templates', module: 'masters', dependencies: [] },
  { featureKey: 'pricingTemplate.view', displayName: 'View Pricing Template', module: 'masters', dependencies: ['pricingTemplate.list'] },
  { featureKey: 'pricingTemplate.create', displayName: 'Create Pricing Template', module: 'masters', dependencies: [], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'pricingTemplate.edit', displayName: 'Edit Pricing Template', module: 'masters', dependencies: ['pricingTemplate.list'] },
  { featureKey: 'pricingTemplate.delete', displayName: 'Delete Pricing Template', module: 'masters', dependencies: ['pricingTemplate.list'] },
  { featureKey: 'group.list', displayName: 'View Product Groups', module: 'product', dependencies: [] },
  { featureKey: 'group.view', displayName: 'View Product Group', module: 'product', dependencies: ['group.list'] },
  { featureKey: 'group.create', displayName: 'Create Product Group', module: 'product', dependencies: [], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'group.edit', displayName: 'Edit Product Group', module: 'product', dependencies: ['group.list'] },
  { featureKey: 'group.delete', displayName: 'Delete Product Group', module: 'product', dependencies: ['group.list'] },
  { featureKey: 'group.publish', displayName: 'Publish/Unpublish Product Groups', module: 'product', dependencies: ['group.list'] },
  { featureKey: 'group.bulk_create', displayName: 'Bulk Create Product Groups', module: 'product', dependencies: ['group.create'] },
  { featureKey: 'variant.list', displayName: 'View Product Variants', module: 'product', dependencies: [] },
  { featureKey: 'variant.view', displayName: 'View Product Variant', module: 'product', dependencies: ['variant.list'] },
  { featureKey: 'variant.create', displayName: 'Create Product Variant', module: 'product', dependencies: [], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'variant.edit', displayName: 'Edit Product Variant', module: 'product', dependencies: ['variant.list'] },
  { featureKey: 'variant.delete', displayName: 'Delete Product Variant', module: 'product', dependencies: ['variant.list'] },
  { featureKey: 'variant.bulk_create', displayName: 'Bulk Create Product Variants', module: 'product', dependencies: ['variant.create'] },
  { featureKey: 'variant.bulk_update', displayName: 'Bulk Update Product Variants', module: 'product', dependencies: ['variant.edit', 'variant.list'] },
  { featureKey: 'pack.list', displayName: 'View Product Packs', module: 'product', dependencies: [] },
  { featureKey: 'pack.view', displayName: 'View Product Pack', module: 'product', dependencies: ['pack.list'] },
  { featureKey: 'pack.create', displayName: 'Create Product Pack', module: 'product', dependencies: [], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'pack.edit', displayName: 'Edit Product Pack', module: 'product', dependencies: ['pack.list'] },
  { featureKey: 'pack.delete', displayName: 'Delete Product Pack', module: 'product', dependencies: ['pack.list'] },
  { featureKey: 'productCollection.list', displayName: 'View Product Collections', module: 'product', dependencies: [] },
  { featureKey: 'productCollection.view', displayName: 'View Product Collection', module: 'product', dependencies: ['productCollection.list'] },
  { featureKey: 'productCollection.create', displayName: 'Create Product Collection', module: 'product', dependencies: ['productCollection.list'], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'productCollection.edit', displayName: 'Edit Product Collection', module: 'product', dependencies: ['productCollection.list'] },
  { featureKey: 'productCollection.delete', displayName: 'Delete Product Collection', module: 'product', dependencies: ['productCollection.list'] },
  { featureKey: 'productCollection.assign', displayName: 'Assign Product Collections', module: 'product', dependencies: ['productCollection.list'] },
  { featureKey: 'stock.list', displayName: 'View Stock', module: 'product', dependencies: [] },
  { featureKey: 'stock.view', displayName: 'View Stock Entry', module: 'product', dependencies: ['stock.list'] },
  { featureKey: 'stock.create', displayName: 'Create Stock Entry', module: 'product', dependencies: [] },
  { featureKey: 'stock.edit', displayName: 'Edit Stock', module: 'product', dependencies: ['stock.list'] },
  { featureKey: 'stock.delete', displayName: 'Delete Stock Entry', module: 'product', dependencies: ['stock.list'] },
  { featureKey: 'stock.bulk_create', displayName: 'Bulk Create Stock Entries', module: 'product', dependencies: ['stock.create'] },
  { featureKey: 'stock.bulk_update', displayName: 'Bulk Update Stock', module: 'product', dependencies: ['stock.edit', 'stock.list'] },
  { featureKey: 'order.list', displayName: 'View Orders', module: 'orders', dependencies: [] },
  { featureKey: 'order.view', displayName: 'View Order', module: 'orders', dependencies: ['order.list'] },
  { featureKey: 'order.create', displayName: 'Create Order', module: 'orders', dependencies: [], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'order.update', displayName: 'Update Orders', module: 'orders', dependencies: ['order.list'] },
  { featureKey: 'order.delete', displayName: 'Delete Order', module: 'orders', dependencies: ['order.list'] },
  { featureKey: 'offer.list', displayName: 'View Offers', module: 'offers', dependencies: [] },
  { featureKey: 'offer.view', displayName: 'View Offer', module: 'offers', dependencies: ['offer.list'] },
  { featureKey: 'offer.create', displayName: 'Create Offer', module: 'offers', dependencies: ['offer.list'], filters: [{ key: 'max_count', defaultValue: 10 }] },
  { featureKey: 'offer.edit', displayName: 'Edit Offer', module: 'offers', dependencies: ['offer.list'] },
  { featureKey: 'offer.delete', displayName: 'Delete Offer', module: 'offers', dependencies: ['offer.list'] },
  { featureKey: 'offer.state', displayName: 'Activate/Pause Offers', module: 'offers', dependencies: ['offer.list'] },
  { featureKey: 'customer.list', displayName: 'View Customers', module: 'customers', dependencies: [] },
  { featureKey: 'customer.view', displayName: 'View Customer', module: 'customers', dependencies: ['customer.list'] },
  { featureKey: 'customer.create', displayName: 'Create Customer', module: 'customers', dependencies: [], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'customer.edit', displayName: 'Edit Customer', module: 'customers', dependencies: ['customer.list'] },
  { featureKey: 'customer.delete', displayName: 'Delete Customer', module: 'customers', dependencies: ['customer.list'] },
  { featureKey: 'customerGroup.list', displayName: 'View Customer Groups', module: 'customers', dependencies: [] },
  { featureKey: 'customerGroup.view', displayName: 'View Customer Group', module: 'customers', dependencies: ['customerGroup.list'] },
  { featureKey: 'customerGroup.create', displayName: 'Create Customer Group', module: 'customers', dependencies: [], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'customerGroup.edit', displayName: 'Edit Customer Group', module: 'customers', dependencies: ['customerGroup.list'] },
  { featureKey: 'customerGroup.delete', displayName: 'Delete Customer Group', module: 'customers', dependencies: ['customerGroup.list'] },
  { featureKey: 'rider.list', displayName: 'View Riders', module: 'delivery', dependencies: [] },
  { featureKey: 'rider.view', displayName: 'View Rider', module: 'delivery', dependencies: ['rider.list'] },
  { featureKey: 'rider.create', displayName: 'Create Rider', module: 'delivery', dependencies: [], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'rider.edit', displayName: 'Edit Rider', module: 'delivery', dependencies: ['rider.list'] },
  { featureKey: 'rider.delete', displayName: 'Delete Rider', module: 'delivery', dependencies: ['rider.list'] },
  { featureKey: 'courierPartner.list', displayName: 'View Courier Partners', module: 'delivery', dependencies: [] },
  { featureKey: 'courierPartner.view', displayName: 'View Courier Partner', module: 'delivery', dependencies: ['courierPartner.list'] },
  { featureKey: 'courierPartner.create', displayName: 'Create Courier Partner', module: 'delivery', dependencies: [], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'courierPartner.edit', displayName: 'Edit Courier Partner', module: 'delivery', dependencies: ['courierPartner.list'] },
  { featureKey: 'courierPartner.delete', displayName: 'Delete Courier Partner', module: 'delivery', dependencies: ['courierPartner.list'] },
  { featureKey: 'dashboard.view', displayName: 'View Dashboard', module: 'settings', dependencies: [] },
  { featureKey: 'tenantAccount.view', displayName: 'View Accounts', module: 'staff-management', dependencies: [] },
  { featureKey: 'tenantAccount.add', displayName: 'Create Account', module: 'staff-management', dependencies: [], filters: [{ key: 'max_count', defaultValue: 10 }] },
  { featureKey: 'tenantAccount.edit', displayName: 'Edit Account', module: 'staff-management', dependencies: ['tenantAccount.view'] },
  { featureKey: 'tenantAccount.delete', displayName: 'Delete Account', module: 'staff-management', dependencies: ['tenantAccount.view'] },
  { featureKey: 'user.list', displayName: 'View Users', module: 'settings', dependencies: [] },
  { featureKey: 'user.view', displayName: 'View User', module: 'settings', dependencies: ['user.list'] },
  { featureKey: 'user.create', displayName: 'Create User', module: 'settings', dependencies: [], filters: [{ key: 'max_count', defaultValue: 100 }] },
  { featureKey: 'user.edit', displayName: 'Edit User', module: 'settings', dependencies: ['user.list'] },
  { featureKey: 'user.delete', displayName: 'Delete User', module: 'settings', dependencies: ['user.list'] },
  { featureKey: 'tenantRole.view', displayName: 'View Roles', module: 'staff-management', dependencies: [] },
  { featureKey: 'tenantRole.add', displayName: 'Create Role', module: 'staff-management', dependencies: [], filters: [{ key: 'max_count', defaultValue: 5 }] },
  { featureKey: 'tenantRole.edit', displayName: 'Edit Role', module: 'staff-management', dependencies: ['tenantRole.view'] },
  { featureKey: 'tenantRole.delete', displayName: 'Delete Role', module: 'staff-management', dependencies: ['tenantRole.view'] },
  { featureKey: 'employeeCode.view', displayName: 'View Employee Code Settings', module: 'settings', dependencies: [] },
  { featureKey: 'employeeCode.config', displayName: 'Configure Employee Code', module: 'settings', dependencies: ['employeeCode.view'] },
  { featureKey: 'notification.broadcast', displayName: 'Send Push Notifications', module: 'settings', dependencies: [] },
  { featureKey: 'notification.manage', displayName: 'Manage Notifications', module: 'settings', dependencies: [] },
  { featureKey: 'storefront.config', displayName: 'Configure Storefront', module: 'settings', dependencies: [] },
  { featureKey: 'storefront.share', displayName: 'Share Storefront', module: 'settings', dependencies: ['storefront.config'] },
  { featureKey: 'pincode.config', displayName: 'Configure Pincodes', module: 'settings', dependencies: [] },
  { featureKey: 'security.config', displayName: 'Configure Security', module: 'settings', dependencies: [] },
  { featureKey: 'returnPolicy.config', displayName: 'Configure Return Policy', module: 'settings', dependencies: [] },
  { featureKey: 'categoryDefaults.view', displayName: 'View Category Defaults', module: 'settings', dependencies: [] },
  { featureKey: 'categoryDefaults.edit', displayName: 'Edit Category Defaults', module: 'settings', dependencies: ['categoryDefaults.view'] },
  { featureKey: 'categoryDefaults.template', displayName: 'Manage Default Templates', module: 'settings', dependencies: ['categoryDefaults.view'] },
  { featureKey: 'template.browse', displayName: 'Browse Templates', module: 'templates', dependencies: [] },
  { featureKey: 'template.subscribe', displayName: 'Subscribe to Template', module: 'templates', dependencies: ['template.browse'] },
  { featureKey: 'template.unsubscribe', displayName: 'Unsubscribe from Template', module: 'templates', dependencies: ['template.browse'] },
  { featureKey: 'media.list', displayName: 'View Media Library', module: 'product', dependencies: [] },
  { featureKey: 'media.upload', displayName: 'Upload Media', module: 'product', dependencies: ['media.list'], filters: [{ key: 'max_images', defaultValue: 10 }, { key: 'max_videos', defaultValue: 1 }] },
  { featureKey: 'media.delete', displayName: 'Delete Media', module: 'product', dependencies: ['media.list'] },
];

export function toFeatureTemplateSyncPayload() {
  return FEATURE_TEMPLATES.map((template) => ({
    featureKey: template.featureKey,
    displayName: template.displayName,
    module: template.module,
    dependencyKeys: [...template.dependencies],
    filters: template.filters ? [...template.filters] : [],
    uiVisibilityPolicy: 'entitled-only' as const,
    status: 'ACTIVE' as const,
    isBeta: false,
  }));
}

export function toFallbackFeatureCatalogItems(): FeatureCatalogItem[] {
  return FEATURE_TEMPLATES.map((template) => ({
    _id: `template:${template.featureKey}`,
    featureKey: template.featureKey,
    displayName: template.displayName,
    module: template.module,
    dependencyKeys: [...template.dependencies],
    filters: template.filters ? [...template.filters] : [],
    planAvailability: ['STARTER', 'GROWTH', 'SCALE'],
    isBeta: false,
    uiVisibilityPolicy: 'entitled-only',
    status: 'ACTIVE',
  }));
}