import { GomSelectOption } from '@gomlibs/ui';

export const CATEGORY_DEFAULT_STATUS = 'ACTIVE' as const;

export const CATEGORY_STATUS_OPTIONS: GomSelectOption[] = [
  { label: 'common.status.active', value: 'ACTIVE' },
  { label: 'common.status.inactive', value: 'INACTIVE' },
];

export const CATEGORY_UI_TEXT = {
  pageTitle: 'categories.title',
  addCategory: 'categories.add',
  actionsLabel: 'common.labels.actions',
  viewAction: 'common.actions.view',
  editAction: 'common.actions.edit',
  deleteAction: 'common.actions.delete',
  searchPlaceholder: 'categories.search',
  emptyMessage: 'categories.empty',
  deleteTitle: 'categories.deleteConfirm.title',
  deleteMessage: 'categories.deleteConfirm.message',
  confirmDelete: 'common.actions.delete',
  cancel: 'common.actions.cancel',
  close: 'common.actions.close',
  closeErrorBanner: 'common.messages.closeErrorBanner',
  detailFallbackTitle: 'categories.details.titleFallback',
  detailCloseAria: 'categories.details.closeAria',
  detailEditAria: 'categories.details.editAria',
  detailDeleteAria: 'categories.details.deleteAria',
  formTitleCreate: 'categories.form.titleCreate',
  formTitleEdit: 'categories.form.titleEdit',
  formSubmitCreate: 'common.actions.create',
  formSubmitUpdate: 'common.actions.update',
  formCancelAria: 'categories.form.cancelAria',
  formCreateAria: 'categories.form.createAria',
  formUpdateAria: 'categories.form.updateAria',
  fieldNameLabel: 'categories.labels.nameRequired',
  fieldNamePlaceholder: 'categories.placeholders.name',
  fieldDescriptionLabel: 'categories.labels.description',
  fieldDescriptionPlaceholder: 'categories.placeholders.description',
  fieldStatusLabel: 'categories.labels.status',
  fieldStatusPlaceholder: 'categories.placeholders.status',
  emptyValue: '-',
  activeStatus: 'ACTIVE',
  statusLabel: 'categories.labels.status',
  nameLabel: 'categories.labels.name',
  descriptionLabel: 'categories.labels.description',
  errorLoad: 'categories.toast.errorLoad',
  errorSave: 'categories.toast.errorSave',
  errorDelete: 'categories.toast.errorDelete',
  errorDeleteMissingId: 'categories.toast.errorDeleteMissingId',
  successCreate: 'categories.toast.successCreate',
  successUpdate: 'categories.toast.successUpdate',
  successDelete: 'categories.toast.successDelete',
  validationNameRequired: 'categories.validation.nameRequired',
  validationNameMin: 'categories.validation.nameMin',
  validationDescriptionMax: 'categories.validation.descriptionMax',
} as const;
